name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "37 13 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Istanbul
          config_output: png
          config_display: large
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_activity: yes
          plugin_calendar: yes
          plugin_calendar_limit: 3
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 300
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_gists: yes
          plugin_habits: yes
          plugin_lines: yes
          plugin_lines_history_limit: 10
          plugin_traffic: yes  
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: activity
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 9287628
          plugin_stackoverflow_sections: answers-top, answers-recent
          plugin_stackoverflow_limit: 8
          
