name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "37 13 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Istanbul
          config_display: large
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_calendar: yes
          plugin_calendar_limit: 4
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 90
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_gists: yes
          plugin_lines: yes
          plugin_lines_history_limit: 10
          plugin_traffic: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 9287628
          plugin_stackoverflow_sections: answers-top, answers-recent
          
